runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: https://github.com/gladstargtschool6/gladstar.sch.ng.git/
  script: index.html

- url: https://github.com/gladstargtschool6/gladstar.sch.ng.git/index\.js
  script: index.html

- url: https://github.com/gladstargtschool6/gladstar.sch.ng.git/stylesheets
  static_dir: stylesheets

- url: https://github.com/gladstargtschool6/gladstar.sch.ng.git/(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: https://github.com/gladstargtschool6/gladstar.sch.ng.git/admin/.*
  script: admin.app
  login: admin

- url: https://github.com/gladstargtschool6/gladstar.sch.ng.git/.*
  script: not_found.app
