
#[start app.yaml]

runtime: python27

api_version: 1

threadsafe: true

handlers:

- url: /

   script: home.app

- url: index/html

   script: home.app

- url: /stylesheets

   static_dir: style.css

- url: /ggts.jpg/

  static_files: static/

  upload: /ggts.jpg/

- url: /admin/*

   script: admin.app

   login: admin

- url: /cron/events/*

  script: [PATH TO APP]

# [END app_yaml]
